In [9]:
import pandas as pd

df = pd.read_csv("emails_clustered_20260924T155915.csv")
df.head()

/tmp/ipykernel_277061/1291166381.py:3: DtypeWarning: Columns (18: Time, 19: Attendees) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("emails_clustered_20260924T155915.csv")

,file,Message-ID,Date,From,To,Cc,Bcc,Subject,Mime-Version,Content-Type,...,date_parsed,body_raw,body,signature,attachment_count,attachment_names,parse_error,full_message,topic,prob_vector
0,allen-p/_sent_mail/1.,<18782981.1075855378110.JavaMail.evans@thyme>,"Mon, 14 May 2001 16:39:00 -0700",phillip.allen@enron.com,tim.belden@enron.com,NaN,NaN,NaN,1.0,"text/plain; charset=""us-ascii""",...,2001-05-14 16:39:00-07:00,Here is our forecast,Here is our forecast,NaN,0,[],NaN,here is our forecast,-1,[0.00074994 0.00125257 0.00143192 0.0011806 0...
1,allen-p/_sent_mail/10.,<15464986.1075855378456.JavaMail.evans@thyme>,"Fri, 04 May 2001 13:51:00 -0700",phillip.allen@enron.com,john.lavorato@enron.com,NaN,NaN,Re:,1.0,"text/plain; charset=""us-ascii""",...,2001-05-04 13:51:00-07:00,Traveling to have a business meeting takes the...,Traveling to have a business meeting takes the...,NaN,0,[],NaN,re traveling to have a business meeting takes ...,-1,[0.0020384 0.01615185 0.00139061 0.00217457 0...
2,allen-p/_sent_mail/100.,<24216240.1075855687451.JavaMail.evans@thyme>,"Wed, 18 Oct 2000 03:00:00 -0700",phillip.allen@enron.com,leah.arsdall@enron.com,NaN,NaN,Re: test,1.0,"text/plain; charset=""us-ascii""",...,2000-10-18 03:00:00-07:00,test successful. way to go!!!,test successful. way to go!!!,NaN,0,[],NaN,re test test successful way to go,223,[1.35173174e-306 4.93564460e-307 2.33858477e-3...
3,allen-p/_sent_mail/1000.,<13505866.1075863688222.JavaMail.evans@thyme>,"Mon, 23 Oct 2000 06:13:00 -0700",phillip.allen@enron.com,randall.gay@enron.com,NaN,NaN,NaN,1.0,"text/plain; charset=""us-ascii""",...,2000-10-23 06:13:00-07:00,"Randy,\n\n Can you send me a schedule of the s...","Randy,\n\n Can you send me a schedule of the s...",Phillip,0,[],NaN,randy can you send me a schedule of the salary...,-1,[0.00114852 0.00281579 0.0007413 0.00113605 0...
4,allen-p/_sent_mail/1001.,<30922949.1075863688243.JavaMail.evans@thyme>,"Thu, 31 Aug 2000 05:07:00 -0700",phillip.allen@enron.com,greg.piper@enron.com,NaN,NaN,Re: Hello,1.0,"text/plain; charset=""us-ascii""",...,2000-08-31 05:07:00-07:00,Let's shoot for Tuesday at 11:45.,Let's shoot for Tuesday at 11:45.,NaN,0,[],NaN,re hello lets shoot for tuesday at 1145,-1,[0.00513134 0.00409018 0.00104967 0.00158061 0...

In [1]:
from bertopic import BERTopic

topic_model = BERTopic.load("emails_clustered_20260924T155915_model.pkl")

/home/marco/development/email-cls-with-clustering/.venv/lib/python3.13/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (7.6.0)/charset_normalizer (2.1.1) doesn't match a supported version!
  warnings.warn(

In [2]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,152714,-1_email_know_subject_gas,"[email, know, subject, gas, pm, information, t...",[do you need a trust schwab signature services...
1,0,2535,0_dont_hey_yes_im,"[dont, hey, yes, im, ok, youre, nice, going, k...","[re i dont know, hi hey good morning, re fw he..."
2,1,2291,1_meeting_staff_meetings_agenda,"[meeting, staff, meetings, agenda, attend, boa...",[staff meeting our next staff meeting is sched...
3,2,2252,2_gas_contract_agreement_natural,"[gas, contract, agreement, natural, deal, mast...",[enron kentucky utilties company gisb addendum...
4,3,1637,3_testimony_motion_intended_subpoena,"[testimony, motion, intended, subpoena, richar...",[nsm update forwarded by richard b sandershoue...
...,...,...,...,...,...
275,274,101,274_ibuyit_eprocurement_payables_invoices,"[ibuyit, eprocurement, payables, invoices, eid...",[action required important ibuyit payables inf...
276,275,101,275_settlement_srp_proposal_epng,"[settlement, srp, proposal, epng, montauk, kil...",[fw srp settlement proposal privileged and con...
277,276,101,276_request_enehouhoustoncommonresearch_resour...,"[request, enehouhoustoncommonresearch, resourc...",[approval is overdue access request for this r...
278,277,100,277_icap_nysrc_wg_nyiso,"[icap, nysrc, wg, nyiso, nyisotechexchange, wr...",[nysrc icap wg conf call 918 writes to the nyi...
279,278,100,278_transwestern_christine_stokes_df,"[transwestern, christine, stokes, df, drew, io...",[re fw transwestern information requests thank...

In [ ]:
topic_model.hierarchical_topics()

In [8]:
hierarchical_topics = topic_model.hierarchical_topics(docs)

TypeError: sequence item 36: expected str instance, float found